<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2013
 *
 * DO NOT EDIT.  Generated by GenCode.php
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';

class CRM_Dmsextension_DAO_Acknowledgement extends CRM_Core_DAO
{
  /**
   * static instance to hold the table name
   *
   * @var string
   * @static
   */
  static $_tableName = 'civicrm_dms_acknowledgement';
  /**
   * static instance to hold the field values
   *
   * @var array
   * @static
   */
  static $_fields = null;
  /**
   * static instance to hold the keys used in $_fields for each field.
   *
   * @var array
   * @static
   */
  static $_fieldKeys = null;
  /**
   * static instance to hold the FK relationships
   *
   * @var string
   * @static
   */
  static $_links = null;
  /**
   * static instance to hold the values that can
   * be imported
   *
   * @var array
   * @static
   */
  static $_import = null;
  /**
   * static instance to hold the values that can
   * be exported
   *
   * @var array
   * @static
   */
  static $_export = null;
  /**
   * static value to see if we should log any modifications to
   * this table in the civicrm_log table
   *
   * @var boolean
   * @static
   */
  static $_log = true;
  
  /**
   * Unique key
   *
   * @var int unsigned
   */
  public $id;
  /**
   * contribution id for the contribution being acknowledged
   *
   * @var int
   */
  public $contribution_id;	
/**
   * Date and time contact was acknowledged for contribution
   *
   * @var datetime
   */
  public $acknowledgement_datetime;	
/**
   * user id who acknowledged the contact
   *
   * @var int
   */
  public $usr_id;	
/**
   * Method of acknowledgement
   *
   * @var varchar
   */
  public $method;	
/**
   * Document name and path of acknowledgement
   *
   * @var varchar
   */
  public $document;	
  
  
  
  function __construct()
  {
    $this->__table = 'civicrm_dms_acknowledgement';
    parent::__construct();
  }
  /**
   * returns all the column names of this table
   *
   * @access public
   * @return array
   */
  static function &fields()
  {
    if (!(self::$_fields)) {
      self::$_fields = array(
       'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('ID') ,
          'required' => true,
        ) ,
        
              'contribution_id' => array(
              'name' => 'contribution_id',
              'title' => ts('contribution id'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

              'acknowledgement_datetime' => array(
              'name' => 'acknowledgement_datetime',
              'title' => ts('acknowledgement datetime'),
              'type' => CRM_Utils_Type::T_DATE,
              
            ) ,	

              'usr_id' => array(
              'name' => 'usr_id',
              'title' => ts('usr id'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

              'method' => array(
              'name' => 'method',
              'title' => ts('method'),
              'type' => CRM_Utils_Type::T_STRING,
              'maxlength' => 100,
            ) ,	

              'document' => array(
              'name' => 'document',
              'title' => ts('document'),
              'type' => CRM_Utils_Type::T_STRING,
              'maxlength' => 255,
            ) ,	

        
      );
    }
    return self::$_fields;
  }
  /**
   * Returns an array containing, for each field, the arary key used for that
   * field in self::$_fields.
   *
   * @access public
   * @return array
   */
  static function &fieldKeys()
  {
    if (!(self::$_fieldKeys)) {
      self::$_fieldKeys = array(
        'id' => 'id',
        'contribution_id' => 'contribution_id',	
'acknowledgement_datetime' => 'acknowledgement_datetime',	
'usr_id' => 'usr_id',	
'method' => 'method',	
'document' => 'document',	

      );
    }
    return self::$_fieldKeys;
  }
  /**
   * returns the names of this table
   *
   * @access public
   * @static
   * @return string
   */
  static function getTableName()
  {
    return self::$_tableName;
  }
  /**
   * returns if this table needs to be logged
   *
   * @access public
   * @return boolean
   */
  function getLog()
  {
    return self::$_log;
  }
  /**
   * returns the list of fields that can be imported
   *
   * @access public
   * return array
   * @static
   */
  static function &import($prefix = false)
  {
    if (!(self::$_import)) {
      self::$_import = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('import', $field)) {
          if ($prefix) {
            self::$_import['dms_acknowledgement'] = & $fields[$name];
          } else {
            self::$_import[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_import;
  }
  /**
   * returns the list of fields that can be exported
   *
   * @access public
   * return array
   * @static
   */
  static function &export($prefix = false)
  {
    if (!(self::$_export)) {
      self::$_export = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('export', $field)) {
          if ($prefix) {
            self::$_export['dms_acknowledgement'] = & $fields[$name];
          } else {
            self::$_export[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_export;
  }
}