<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2013
 *
 * DO NOT EDIT.  Generated by GenCode.php
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';

class CRM_Dmsextension_DAO_BatchEntry extends CRM_Core_DAO
{
  /**
   * static instance to hold the table name
   *
   * @var string
   * @static
   */
  static $_tableName = 'civicrm_dms_batch_entry';
  /**
   * static instance to hold the field values
   *
   * @var array
   * @static
   */
  static $_fields = null;
  /**
   * static instance to hold the keys used in $_fields for each field.
   *
   * @var array
   * @static
   */
  static $_fieldKeys = null;
  /**
   * static instance to hold the FK relationships
   *
   * @var string
   * @static
   */
  static $_links = null;
  /**
   * static instance to hold the values that can
   * be imported
   *
   * @var array
   * @static
   */
  static $_import = null;
  /**
   * static instance to hold the values that can
   * be exported
   *
   * @var array
   * @static
   */
  static $_export = null;
  /**
   * static value to see if we should log any modifications to
   * this table in the civicrm_log table
   *
   * @var boolean
   * @static
   */
  static $_log = true;
  
  /**
   * Unique key
   *
   * @var int unsigned
   */
  public $id;
  /**
   * id in the civicrm_dms_batch_header table
   *
   * @var int
   */
  public $batch_id;	
/**
   * date and time the batch entry was created
   *
   * @var datetime
   */
  public $received_datetime;	
/**
   * User Id that created the batch entry
   *
   * @var int
   */
  public $received_by;	
/**
   * Receipt no for the entry
   *
   * @var int
   */
  public $receipt_no;	
/**
   * Amount Received
   *
   * @var decimal
   */
  public $receipt_amount;	
/**
   * Receipt/Document type
   *
   * @var varchar
   */
  public $receipt_type;	
  
  
  
  function __construct()
  {
    $this->__table = 'civicrm_dms_batch_entry';
    parent::__construct();
  }
  /**
   * returns all the column names of this table
   *
   * @access public
   * @return array
   */
  static function &fields()
  {
    if (!(self::$_fields)) {
      self::$_fields = array(
       'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('ID') ,
          'required' => true,
        ) ,
        
              'batch_id' => array(
              'name' => 'batch_id',
              'title' => ts('batch id'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

              'received_datetime' => array(
              'name' => 'received_datetime',
              'title' => ts('received datetime'),
              'type' => CRM_Utils_Type::T_DATE,
              
            ) ,	

              'received_by' => array(
              'name' => 'received_by',
              'title' => ts('received by'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

              'receipt_no' => array(
              'name' => 'receipt_no',
              'title' => ts('receipt no'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

              'receipt_amount' => array(
              'name' => 'receipt_amount',
              'title' => ts('receipt amount'),
              'type' => CRM_Utils_Type::T_MONEY,
              
            ) ,	

              'receipt_type' => array(
              'name' => 'receipt_type',
              'title' => ts('receipt type'),
              'type' => CRM_Utils_Type::T_STRING,
              'maxlength' => 50,
            ) ,	

        
      );
    }
    return self::$_fields;
  }
  /**
   * Returns an array containing, for each field, the arary key used for that
   * field in self::$_fields.
   *
   * @access public
   * @return array
   */
  static function &fieldKeys()
  {
    if (!(self::$_fieldKeys)) {
      self::$_fieldKeys = array(
        'id' => 'id',
        'batch_id' => 'batch_id',	
'received_datetime' => 'received_datetime',	
'received_by' => 'received_by',	
'receipt_no' => 'receipt_no',	
'receipt_amount' => 'receipt_amount',	
'receipt_type' => 'receipt_type',	

      );
    }
    return self::$_fieldKeys;
  }
  /**
   * returns the names of this table
   *
   * @access public
   * @static
   * @return string
   */
  static function getTableName()
  {
    return self::$_tableName;
  }
  /**
   * returns if this table needs to be logged
   *
   * @access public
   * @return boolean
   */
  function getLog()
  {
    return self::$_log;
  }
  /**
   * returns the list of fields that can be imported
   *
   * @access public
   * return array
   * @static
   */
  static function &import($prefix = false)
  {
    if (!(self::$_import)) {
      self::$_import = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('import', $field)) {
          if ($prefix) {
            self::$_import['dms_batch_entry'] = & $fields[$name];
          } else {
            self::$_import[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_import;
  }
  /**
   * returns the list of fields that can be exported
   *
   * @access public
   * return array
   * @static
   */
  static function &export($prefix = false)
  {
    if (!(self::$_export)) {
      self::$_export = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('export', $field)) {
          if ($prefix) {
            self::$_export['dms_batch_entry'] = & $fields[$name];
          } else {
            self::$_export[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_export;
  }
}