<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2013
 *
 * DO NOT EDIT.  Generated by GenCode.php
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';

class CRM_Dmsextension_DAO_ContactOtherData extends CRM_Core_DAO
{
  /**
   * static instance to hold the table name
   *
   * @var string
   * @static
   */
  static $_tableName = 'civicrm_dms_contact_other_data';
  /**
   * static instance to hold the field values
   *
   * @var array
   * @static
   */
  static $_fields = null;
  /**
   * static instance to hold the keys used in $_fields for each field.
   *
   * @var array
   * @static
   */
  static $_fieldKeys = null;
  /**
   * static instance to hold the FK relationships
   *
   * @var string
   * @static
   */
  static $_links = null;
  /**
   * static instance to hold the values that can
   * be imported
   *
   * @var array
   * @static
   */
  static $_import = null;
  /**
   * static instance to hold the values that can
   * be exported
   *
   * @var array
   * @static
   */
  static $_export = null;
  /**
   * static value to see if we should log any modifications to
   * this table in the civicrm_log table
   *
   * @var boolean
   * @static
   */
  static $_log = true;
  
  /**
   * Unique key
   *
   * @var int unsigned
   */
  public $id;
  /**
   * Contact Id from the civicrm_contact table
   *
   * @var int
   */
  public $contact_id;	
/**
   * Temporary Acknowledgement Flag - Does Contact want to be acknowledged for contributions?
   *
   * @var tinyint
   */
  public $do_not_thank;	
/**
   * Month contact must reminded of debit order renewal
   *
   * @var tinyint
   */
  public $reminder_month;	
/**
   * South African ID number
   *
   * @var varchar
   */
  public $id_number;	
/**
   * Last time contact made a contribution
   *
   * @var datetime
   */
  public $last_contribution_date;	
/**
   * Last contribution amount
   *
   * @var decimal
   */
  public $last_contribution_amount;	
/**
   * User who created the contact
   *
   * @var int
   */
  public $inserted_by_contact_id;	
/**
   * User who last modified the contact
   *
   * @var int
   */
  public $modified_by_contact_id;	
  
  
  
  function __construct()
  {
    $this->__table = 'civicrm_dms_contact_other_data';
    parent::__construct();
  }
  /**
   * returns all the column names of this table
   *
   * @access public
   * @return array
   */
  static function &fields()
  {
    if (!(self::$_fields)) {
      self::$_fields = array(
       'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('ID') ,
          'required' => true,
        ) ,
        
              'contact_id' => array(
              'name' => 'contact_id',
              'title' => ts('contact id'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

              'do_not_thank' => array(
              'name' => 'do_not_thank',
              'title' => ts('do not thank'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

              'reminder_month' => array(
              'name' => 'reminder_month',
              'title' => ts('reminder month'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

              'id_number' => array(
              'name' => 'id_number',
              'title' => ts('id number'),
              'type' => CRM_Utils_Type::T_STRING,
              'maxlength' => 15,
            ) ,	

              'last_contribution_date' => array(
              'name' => 'last_contribution_date',
              'title' => ts('last contribution date'),
              'type' => CRM_Utils_Type::T_DATE,
              
            ) ,	

              'last_contribution_amount' => array(
              'name' => 'last_contribution_amount',
              'title' => ts('last contribution amount'),
              'type' => CRM_Utils_Type::T_MONEY,
              
            ) ,	

              'inserted_by_contact_id' => array(
              'name' => 'inserted_by_contact_id',
              'title' => ts('inserted by contact id'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

              'modified_by_contact_id' => array(
              'name' => 'modified_by_contact_id',
              'title' => ts('modified by contact id'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

        
      );
    }
    return self::$_fields;
  }
  /**
   * Returns an array containing, for each field, the arary key used for that
   * field in self::$_fields.
   *
   * @access public
   * @return array
   */
  static function &fieldKeys()
  {
    if (!(self::$_fieldKeys)) {
      self::$_fieldKeys = array(
        'id' => 'id',
        'contact_id' => 'contact_id',	
'do_not_thank' => 'do_not_thank',	
'reminder_month' => 'reminder_month',	
'id_number' => 'id_number',	
'last_contribution_date' => 'last_contribution_date',	
'last_contribution_amount' => 'last_contribution_amount',	
'inserted_by_contact_id' => 'inserted_by_contact_id',	
'modified_by_contact_id' => 'modified_by_contact_id',	

      );
    }
    return self::$_fieldKeys;
  }
  /**
   * returns the names of this table
   *
   * @access public
   * @static
   * @return string
   */
  static function getTableName()
  {
    return self::$_tableName;
  }
  /**
   * returns if this table needs to be logged
   *
   * @access public
   * @return boolean
   */
  function getLog()
  {
    return self::$_log;
  }
  /**
   * returns the list of fields that can be imported
   *
   * @access public
   * return array
   * @static
   */
  static function &import($prefix = false)
  {
    if (!(self::$_import)) {
      self::$_import = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('import', $field)) {
          if ($prefix) {
            self::$_import['dms_contact_other_data'] = & $fields[$name];
          } else {
            self::$_import[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_import;
  }
  /**
   * returns the list of fields that can be exported
   *
   * @access public
   * return array
   * @static
   */
  static function &export($prefix = false)
  {
    if (!(self::$_export)) {
      self::$_export = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('export', $field)) {
          if ($prefix) {
            self::$_export['dms_contact_other_data'] = & $fields[$name];
          } else {
            self::$_export[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_export;
  }
}