<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2013
 *
 * DO NOT EDIT.  Generated by GenCode.php
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';

class CRM_Dmsextension_DAO_NextBudget extends CRM_Core_DAO
{
  /**
   * static instance to hold the table name
   *
   * @var string
   * @static
   */
  static $_tableName = 'civicrm_dms_next_budget';
  /**
   * static instance to hold the field values
   *
   * @var array
   * @static
   */
  static $_fields = null;
  /**
   * static instance to hold the keys used in $_fields for each field.
   *
   * @var array
   * @static
   */
  static $_fieldKeys = null;
  /**
   * static instance to hold the FK relationships
   *
   * @var string
   * @static
   */
  static $_links = null;
  /**
   * static instance to hold the values that can
   * be imported
   *
   * @var array
   * @static
   */
  static $_import = null;
  /**
   * static instance to hold the values that can
   * be exported
   *
   * @var array
   * @static
   */
  static $_export = null;
  /**
   * static value to see if we should log any modifications to
   * this table in the civicrm_log table
   *
   * @var boolean
   * @static
   */
  static $_log = true;
  
  /**
   * Unique key
   *
   * @var int unsigned
   */
  public $id;
  /**
   * region that the budget belongs to
   *
   * @var int
   */
  public $bud_region;	
/**
   * Department the budget belongs to
   *
   * @var varchar
   */
  public $bud_department;	
/**
   * Category the budget belongs to
   *
   * @var int
   */
  public $bud_category;	
/**
   * Budget Amount
   *
   * @var decimal
   */
  public $bud_amount;	
/**
   * User who inserted the budget
   *
   * @var varchar
   */
  public $bud_insert_user;	
/**
   * date and time the budget was inserted
   *
   * @var datetime
   */
  public $bud_dateinserted;	
/**
   * date and time the budget was last updated
   *
   * @var datetime
   */
  public $bud_datelastupdated;	
/**
   * User who last updated the budget
   *
   * @var varchar
   */
  public $bud_update_user;	
  
  
  
  function __construct()
  {
    $this->__table = 'civicrm_dms_next_budget';
    parent::__construct();
  }
  /**
   * returns all the column names of this table
   *
   * @access public
   * @return array
   */
  static function &fields()
  {
    if (!(self::$_fields)) {
      self::$_fields = array(
       'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('ID') ,
          'required' => true,
        ) ,
        
              'bud_region' => array(
              'name' => 'bud_region',
              'title' => ts('bud region'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

              'bud_department' => array(
              'name' => 'bud_department',
              'title' => ts('bud department'),
              'type' => CRM_Utils_Type::T_STRING,
              'maxlength' => 2,
            ) ,	

              'bud_category' => array(
              'name' => 'bud_category',
              'title' => ts('bud category'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

              'bud_amount' => array(
              'name' => 'bud_amount',
              'title' => ts('bud amount'),
              'type' => CRM_Utils_Type::T_MONEY,
              
            ) ,	

              'bud_insert_user' => array(
              'name' => 'bud_insert_user',
              'title' => ts('bud insert user'),
              'type' => CRM_Utils_Type::T_STRING,
              'maxlength' => 200,
            ) ,	

              'bud_dateinserted' => array(
              'name' => 'bud_dateinserted',
              'title' => ts('bud dateinserted'),
              'type' => CRM_Utils_Type::T_DATE,
              
            ) ,	

              'bud_datelastupdated' => array(
              'name' => 'bud_datelastupdated',
              'title' => ts('bud datelastupdated'),
              'type' => CRM_Utils_Type::T_DATE,
              
            ) ,	

              'bud_update_user' => array(
              'name' => 'bud_update_user',
              'title' => ts('bud update user'),
              'type' => CRM_Utils_Type::T_STRING,
              'maxlength' => 200,
            ) ,	

        
      );
    }
    return self::$_fields;
  }
  /**
   * Returns an array containing, for each field, the arary key used for that
   * field in self::$_fields.
   *
   * @access public
   * @return array
   */
  static function &fieldKeys()
  {
    if (!(self::$_fieldKeys)) {
      self::$_fieldKeys = array(
        'id' => 'id',
        'bud_region' => 'bud_region',	
'bud_department' => 'bud_department',	
'bud_category' => 'bud_category',	
'bud_amount' => 'bud_amount',	
'bud_insert_user' => 'bud_insert_user',	
'bud_dateinserted' => 'bud_dateinserted',	
'bud_datelastupdated' => 'bud_datelastupdated',	
'bud_update_user' => 'bud_update_user',	

      );
    }
    return self::$_fieldKeys;
  }
  /**
   * returns the names of this table
   *
   * @access public
   * @static
   * @return string
   */
  static function getTableName()
  {
    return self::$_tableName;
  }
  /**
   * returns if this table needs to be logged
   *
   * @access public
   * @return boolean
   */
  function getLog()
  {
    return self::$_log;
  }
  /**
   * returns the list of fields that can be imported
   *
   * @access public
   * return array
   * @static
   */
  static function &import($prefix = false)
  {
    if (!(self::$_import)) {
      self::$_import = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('import', $field)) {
          if ($prefix) {
            self::$_import['dms_next_budget'] = & $fields[$name];
          } else {
            self::$_import[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_import;
  }
  /**
   * returns the list of fields that can be exported
   *
   * @access public
   * return array
   * @static
   */
  static function &export($prefix = false)
  {
    if (!(self::$_export)) {
      self::$_export = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('export', $field)) {
          if ($prefix) {
            self::$_export['dms_next_budget'] = & $fields[$name];
          } else {
            self::$_export[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_export;
  }
}