<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2013
 *
 * DO NOT EDIT.  Generated by GenCode.php
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';

class CRM_Dmsextension_DAO_Region extends CRM_Core_DAO
{
  /**
   * static instance to hold the table name
   *
   * @var string
   * @static
   */
  static $_tableName = 'civicrm_dms_region';
  /**
   * static instance to hold the field values
   *
   * @var array
   * @static
   */
  static $_fields = null;
  /**
   * static instance to hold the keys used in $_fields for each field.
   *
   * @var array
   * @static
   */
  static $_fieldKeys = null;
  /**
   * static instance to hold the FK relationships
   *
   * @var string
   * @static
   */
  static $_links = null;
  /**
   * static instance to hold the values that can
   * be imported
   *
   * @var array
   * @static
   */
  static $_import = null;
  /**
   * static instance to hold the values that can
   * be exported
   *
   * @var array
   * @static
   */
  static $_export = null;
  /**
   * static value to see if we should log any modifications to
   * this table in the civicrm_log table
   *
   * @var boolean
   * @static
   */
  static $_log = true;
  
  /**
   * Unique key
   *
   * @var int unsigned
   */
  public $id;
  /**
   * region id
   *
   * @var int
   */
  public $reg_id;	
/**
   * region name
   *
   * @var varchar
   */
  public $reg_name;	
/**
   * id for the consol file for the consol report.
   *
   * @var int
   */
  public $reg_consol_id;	
/**
   * Group id linked to the region
   *
   * @var int
   */
  public $reg_joomla_group_id;	
/**
   * Office Id that this region is linked to
   *
   * @var int
   */
  public $reg_office_id;	
  
  
  
  function __construct()
  {
    $this->__table = 'civicrm_dms_region';
    parent::__construct();
  }
  /**
   * returns all the column names of this table
   *
   * @access public
   * @return array
   */
  static function &fields()
  {
    if (!(self::$_fields)) {
      self::$_fields = array(
       'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('ID') ,
          'required' => true,
        ) ,
        
              'reg_id' => array(
              'name' => 'reg_id',
              'title' => ts('reg id'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

              'reg_name' => array(
              'name' => 'reg_name',
              'title' => ts('reg name'),
              'type' => CRM_Utils_Type::T_STRING,
              'maxlength' => 50,
            ) ,	

              'reg_consol_id' => array(
              'name' => 'reg_consol_id',
              'title' => ts('reg consol id'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

              'reg_joomla_group_id' => array(
              'name' => 'reg_joomla_group_id',
              'title' => ts('reg joomla group id'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

              'reg_office_id' => array(
              'name' => 'reg_office_id',
              'title' => ts('reg office id'),
              'type' => CRM_Utils_Type::T_INT,
              
            ) ,	

        
      );
    }
    return self::$_fields;
  }
  /**
   * Returns an array containing, for each field, the arary key used for that
   * field in self::$_fields.
   *
   * @access public
   * @return array
   */
  static function &fieldKeys()
  {
    if (!(self::$_fieldKeys)) {
      self::$_fieldKeys = array(
        'id' => 'id',
        'reg_id' => 'reg_id',	
'reg_name' => 'reg_name',	
'reg_consol_id' => 'reg_consol_id',	
'reg_joomla_group_id' => 'reg_joomla_group_id',	
'reg_office_id' => 'reg_office_id',	

      );
    }
    return self::$_fieldKeys;
  }
  /**
   * returns the names of this table
   *
   * @access public
   * @static
   * @return string
   */
  static function getTableName()
  {
    return self::$_tableName;
  }
  /**
   * returns if this table needs to be logged
   *
   * @access public
   * @return boolean
   */
  function getLog()
  {
    return self::$_log;
  }
  /**
   * returns the list of fields that can be imported
   *
   * @access public
   * return array
   * @static
   */
  static function &import($prefix = false)
  {
    if (!(self::$_import)) {
      self::$_import = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('import', $field)) {
          if ($prefix) {
            self::$_import['dms_region'] = & $fields[$name];
          } else {
            self::$_import[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_import;
  }
  /**
   * returns the list of fields that can be exported
   *
   * @access public
   * return array
   * @static
   */
  static function &export($prefix = false)
  {
    if (!(self::$_export)) {
      self::$_export = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('export', $field)) {
          if ($prefix) {
            self::$_export['dms_region'] = & $fields[$name];
          } else {
            self::$_export[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_export;
  }
}