<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2013
 *
 * DO NOT EDIT.  Generated by GenCode.php
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';

class CRM_Dmsextension_DAO_Transaction extends CRM_Core_DAO
{
  /**
   * static instance to hold the table name
   *
   * @var string
   * @static
   */
  static $_tableName = 'civicrm_dms_transaction';
  /**
   * static instance to hold the field values
   *
   * @var array
   * @static
   */
  static $_fields = null;
  /**
   * static instance to hold the keys used in $_fields for each field.
   *
   * @var array
   * @static
   */
  static $_fieldKeys = null;
  /**
   * static instance to hold the FK relationships
   *
   * @var string
   * @static
   */
  static $_links = null;
  /**
   * static instance to hold the values that can
   * be imported
   *
   * @var array
   * @static
   */
  static $_import = null;
  /**
   * static instance to hold the values that can
   * be exported
   *
   * @var array
   * @static
   */
  static $_export = null;
  /**
   * static value to see if we should log any modifications to
   * this table in the civicrm_log table
   *
   * @var boolean
   * @static
   */
  static $_log = true;
  
  /**
   * Unique key
   *
   * @var int unsigned
   */
  public $id;
  /**
   * Contribution Id
   *
   * @var int unsigned
   */
  public $contribution_id;
  /**
   * Motivation Id
   *
   * @var string
   */
  public $motivation_id;
  /**
   * Category Id
   *
   * @var string
   */
  public $category_id;
  /**
   * Region Id
   *
   * @var string
   */
  public $region_id;
  /**
   * Organisation Id
   *
   * @var string
   */
  public $organisation_id;

  /**
   * class constructor
   *
   * @access public
   * @return civicrm_dms_region
   */
  function __construct()
  {
    $this->__table = 'civicrm_dms_transaction';
    parent::__construct();
  }
  /**
   * returns all the column names of this table
   *
   * @access public
   * @return array
   */
  static function &fields()
  {
    if (!(self::$_fields)) {
      self::$_fields = array(
       'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('ID') ,
          'required' => true,
        ) ,
        'contribution_id' => array(
          'name' => 'contribution_id',
          'title' => ts('Contribution Id'),
          'type' => CRM_Utils_Type::T_INT,
        ) ,
        'motivation_id' => array(
          'name' => 'motivation_id',
          'title' => ts('Motivation Id'),
          'type' => CRM_Utils_Type::T_INT,
        ) ,
        'category_id' => array(
          'name' => 'category_id',
          'title' => ts('Category Id'),
          'type' => CRM_Utils_Type::T_STRING,
          'maxlength' => 4,
        ) ,
        'region_id' => array(
          'name' => 'region_id',
          'title' => ts('Region Id'),
          'type' => CRM_Utils_Type::T_INT,
        ) ,
        'organisation_id' => array(
          'name' => 'organisation_id',
          'title' => ts('Organisation Id'),
          'type' => CRM_Utils_Type::T_STRING,
          'maxlength' => 8,
        ) ,
      );
    }
    return self::$_fields;
  }
  /**
   * Returns an array containing, for each field, the arary key used for that
   * field in self::$_fields.
   *
   * @access public
   * @return array
   */
  static function &fieldKeys()
  {
    if (!(self::$_fieldKeys)) {
      self::$_fieldKeys = array(
        'id' => 'id',
        'contribution_id' => 'contribution_id',
        'motivation_id' => 'motivation_id',
        'organisation_id' => 'organisation_id',
        'region_id' => 'region_id',
        'category_id' => 'category_id',
      );
    }
    return self::$_fieldKeys;
  }
  /**
   * returns the names of this table
   *
   * @access public
   * @static
   * @return string
   */
  static function getTableName()
  {
    return self::$_tableName;
  }
  /**
   * returns if this table needs to be logged
   *
   * @access public
   * @return boolean
   */
  function getLog()
  {
    return self::$_log;
  }
  /**
   * returns the list of fields that can be imported
   *
   * @access public
   * return array
   * @static
   */
  static function &import($prefix = false)
  {
    if (!(self::$_import)) {
      self::$_import = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('import', $field)) {
          if ($prefix) {
            self::$_import['dms_transaction'] = & $fields[$name];
          } else {
            self::$_import[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_import;
  }
  /**
   * returns the list of fields that can be exported
   *
   * @access public
   * return array
   * @static
   */
  static function &export($prefix = false)
  {
    if (!(self::$_export)) {
      self::$_export = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('export', $field)) {
          if ($prefix) {
            self::$_export['dms_transaction'] = & $fields[$name];
          } else {
            self::$_export[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_export;
  }
}